module.exports = [
    { title: "Wake up!",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [5, "zouro"],
        [7, "zouro"],
        [9, "zouro"],
        [13, "zouro"],
        [18, "zouro"],
        [19, "zouro"],
        [20, "zouro"],
        [21, "zouro"]
      ] },
    { title: "This parking lot is dangerous",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [5, "zouro"],
        [7, "zouro"],
        [9, "zouro"],
        [13, "zouro"],
        [13, "zouro"],
        [16, "zouro"],
        [18, "zouro"],
        [20, "zouro"],
        [24, "zouro"],
        [24, "zouro"]
      ] },
    { title: "Do it for Rose",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [3, "zouro"],
        [4, "zouro"],
        [8, "zouro"],
        [8, "zouro"],
        [8, "zouro"],
        [10, "zouro"],
        [14, "zouro"],
        [14, "zouro"],
        [19, "zouro"],
        [19, "zouro"],
        [19, "zouro"],
        [19, "zouro"]
      ] },
    { title: "Smart Pipes, Lookout",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [8, "ouno"],
        [13, "zouro"],
        [13, "zouro"],
        [16, "zouro"],
        [18, "ouno"],
        [22, "zouro"],
        [22, "zouro"],
        [22, "zouro"],
        [26, "ouno"],
        [26, "ouno"]
      ] },
    { title: "Shoot it don't snort it",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [3, "zouro"],
        [7, "zouro"],
        [7, "trouo"],
        [8, "zouro"],
        [9, "trouo"],
        [12, "zouro"],
        [12, "zouro"],
        [12, "zouro"],
        [12, "zouro"],
        [15, "ouno"],
        [15, "ouno"],
      ] },
    { title: "Do coke instead, K?",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [2, "zouro"],
        [4, "zouro"],
        [4, "zouro"],
        [8, "zouro"],
        [8, "ouno"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [22, "trouo"],
        [22, "trouo"],
        [22, "trouo"],
        [22, "trouo"],
        [26, "ouno"],
        [26, "ouno"],
      ] },
    { title: "Try energy drinks",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [6, "ouno"],
        [6, "ouno"],
        [7, "zouro"],
        [8, "zouro"],
        [9, "ouno"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "ouno"],
        [20, "zouro"],
        [20, "ouno"],
        [26, "douo"],
      ] },
    { title: "Dont hit the Crown Vic!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [6, "ouno"],
        [6, "ouno"],
        [7, "zouro"],
        [8, "zouro"],
        [10, "douo"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "ouno"],
        [20, "trouo"],
        [20, "trouo"],
        [20, "trouo"],
        [20, "trouo"],
        [24, "douo"],
        [26, "douo"],
        [26, "douo"],
      ] },

  ];

